config/routes.rb
OnlineCinemaTicket::Application.routes.draw do

  resources :order_lines

  resources :orders

  resources :administrators

  controller :administrators do
    get 'admin' => :admin
  end

  resources :actors

  controller :sessions do
    get 'admin_login'  => :admin_new
    post 'admin_login' => :admin_create
    get 'login'        => :new
    post 'login'       => :create
    delete 'logout'    => :destroy
  end

  resources :store

  controller :store do
    get 'index'      => :index
    get 'show_now'   => :show_now
    get 'show_after' => :show_after
    get 'about'      => :about
  end
    
  resources :accounts 

  controller :accounts do
    get 'newuser' => :new
    get 'detail'  => :detail
  end

  controller :choose do
    get 'show_ticket' => :show_ticket
    get 'show_seat'   => :show_seat
    post 'ensure_order' => :ensure_order
    get 'ensure_order' => :ensure_order
  end
  
  resources :tickets

  resources :films

  controller :film do
    get 'moreinfo' => :moreinfo
  end

  resources :about

  root :to => 'store#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/film.rb
#encoding: utf-8
class Film < ActiveRecord::Base
  attr_accessible :category, :country, :description, :director, :length, :time, :title
  has_many :actors
  has_many :tickets

  validates_presence_of :title, :message => "电影标题不能为空"
    
  
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_filter :authorize, :except => :show
  # GET /films
  # GET /films.json
  def index
    @films = Film.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @films }
    end
  end

  # GET /films/1
  # GET /films/1.json
  def show
    @film = Film.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @film }
    end
  end

  # GET /films/new
  # GET /films/new.json
  def new
    @film = Film.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @film }
    end
  end

  # GET /films/1/edit
  def edit
    @film = Film.find(params[:id])
  end

  # POST /films
  # POST /films.json
  def create
    @film = Film.new(params[:film])
    actornames = params[:actors].split(',')
    actornames.each do |actorname|
      actor = Actor.new
      actor.film_id = @film.id
      actor.name = actorname
      @film.actors << actor
    end

    respond_to do |format|
      if @film.save
        format.html { redirect_to @film, notice: 'Film was successfully created.' }
        format.json { render json: @film, status: :created, location: @film }
      else
        format.html { render action: "new" }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /films/1
  # PUT /films/1.json
  def update
    @film = Film.find(params[:id])
    actornames = params[:actors].split(',')
    actornames.each do |actorname|
      actor = Actor.new
      actor.film_id = @film.id
      actor.name = actorname
      @film.actors << actor
    end


    respond_to do |format|
      if @film.update_attributes(params[:film])
        format.html { redirect_to @film, notice: 'Film was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1
  # DELETE /films/1.json
  def destroy
    @film = Film.find(params[:id])
    @film.tickets.destroy_all
    @film.actors.destroy_all
    @film.destroy

    respond_to do |format|
      format.html { redirect_to films_url }
      format.json { head :no_content }
    end
  end

  def moreinfo
  end
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/films/_form.html.erb
<%= form_for(@film) do |f| %>
  <% if @film.errors.any? %>
    <div id="error_explanation">
      <h2><%=@film.errors.count %>个错误被发现，请重新填写！ </h2>

      <ul>
      <% @film.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, '电影标题' %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :director, '导演' %><br />
    <%= f.text_field :director %>
  </div>
  <div class="field">
    <%= label_tag :actors, '演员' %><br />
    <%= text_field_tag :actors %>
  </div>
  <div class="field">
    <%= f.label :country, '地区' %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :length, '片长' %><br />
    <%= f.number_field :length %>
  </div>
  <div class="field">
    <%= f.label :time, '上映日期' %><br />
    <%= f.date_select :time %>
  </div>
  <div class="field">
    <%= f.label :description, '影片描述' %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/films/edit.html.erb
<h1>编辑电影</h1>

<%= render 'form' %>

<%= link_to '详细信息', @film %> |
<%= link_to '返回', films_path %>

app/views/films/index.html.erb
<style type="text/css" media="screen">
.span6 img {
  float: left;
}

.dir {
  margin-left: 16em;
}
.dir h4, .dir p {
  display: inline;    
}
.btn {
  float: bottom;
}
</style>

<% cnt = 0 %>
<% @films.each do |film| %>
  <% if cnt % 2 == 0 %>
    <div class="row">
  <% end %>

  <div class="span6" %>
    <table class="table table-bordered">
      <tr><td>
          <%= image_tag '/images/'+film.title+'.jpeg' %>
          <div class="dir">
            <h3><%= film.title %></h3>
          </div>
          <div class="dir">
            <h4>导演：</h4>
            <p><%= film.director %></p>
          </div>
          <div class="dir">
            <h4>地区：</h4>
            <p><%= film.country %></p>
          </div>
          <div class="dir">
            <h4>片长：</h4>
            <p><%= film.length %>分钟</p>
          </div>
          <div class="dir">
            <h4>上映时间：</h4>
            <p><%= film.time %></p>
          </div>
          <div class="dir">
            <h4>剧情简介：</h4>
            <p><%= film.description.slice(0,90)+'......' %></p>
          </div>
          <div class="dir">
            <%= link_to '详细信息', film %>
            <%= link_to '编辑', edit_film_path(film) %>
            <%= link_to '删除', film, method: :delete, data: { confirm: '确定删除？' } %>
          </div>
      </td></tr>
    </table>
  </div>

  <% if cnt % 2 == 1 %>
  </div>
  <% end %>
  <% cnt += 1 %>
<% end %>

<% if cnt % 2 == 1 %>
</div>
<% end %>


<div class="row">
  <%= link_to '添加新电影', new_film_path %>
</div>

app/views/films/new.html.erb
<h1>添加新电影</h1>

<%= render 'form' %>

<%= link_to 'Back', films_path %>

app/views/films/show.html.erb
<style type="text/css" media="screen">
b {
  font-size: 1.5em;
}
  
</style>
<h1>详细信息</h1><br/>
<p>
  <b>影片名称</b>
  <%= @film.title %>
</p>

<p>
  <b>导演</b>
  <%= @film.director %>
</p>
<p>
  <b>演员</b>
  <% @film.actors.each do |actor| %>
  <%= actor.name %>
  <% end %>
</p>

<p>
  <b>地区</b>
  <%= @film.country %>
</p>

<p>
  <b>片长</b>
  <%= @film.length %>
  分钟
</p>

<p>
  <b>上映日期</b>
  <%= @film.time %>
</p>

<p>
  <b>影片描述</b>
  <%= @film.description %>
</p>