config/routes.rb
OnlineCinemaTicket::Application.routes.draw do

  resources :order_lines

  resources :orders

  resources :administrators

  controller :administrators do
    get 'admin' => :admin
  end

  resources :actors

  controller :sessions do
    get 'admin_login'  => :admin_new
    post 'admin_login' => :admin_create
    get 'login'        => :new
    post 'login'       => :create
    delete 'logout'    => :destroy
  end

  resources :store

  controller :store do
    get 'index'      => :index
    get 'show_now'   => :show_now
    get 'show_after' => :show_after
    get 'about'      => :about
  end
    
  resources :accounts 

  controller :accounts do
    get 'newuser' => :new
    get 'detail'  => :detail
  end

  controller :choose do
    get 'show_ticket' => :show_ticket
    get 'show_seat'   => :show_seat
    post 'ensure_order' => :ensure_order
    get 'ensure_order' => :ensure_order
  end
  
  resources :tickets

  resources :films

  controller :film do
    get 'moreinfo' => :moreinfo
  end

  resources :about

  root :to => 'store#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
  attr_accessible :password, :password_confirmation, :username
  has_secure_password
end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
  # GET /administrators
  # GET /administrators.json
  def index
    @administrators = Administrator.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @administrators }
    end
  end

  # GET /administrators/1
  # GET /administrators/1.json
  def show
    @administrator = Administrator.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @administrator }
    end
  end

  # GET /administrators/new
  # GET /administrators/new.json
  def new
    @administrator = Administrator.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @administrator }
    end
  end

  # GET /administrators/1/edit
  def edit
    @administrator = Administrator.find(params[:id])
  end

  # POST /administrators
  # POST /administrators.json
  def create
    @administrator = Administrator.new(params[:administrator])

    respond_to do |format|
      if @administrator.save
        format.html { redirect_to @administrator, notice: 'Administrator was successfully created.' }
        format.json { render json: @administrator, status: :created, location: @administrator }
      else
        format.html { render action: "new" }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /administrators/1
  # PUT /administrators/1.json
  def update
    @administrator = Administrator.find(params[:id])

    respond_to do |format|
      if @administrator.update_attributes(params[:administrator])
        format.html { redirect_to @administrator, notice: 'Administrator was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administrators/1
  # DELETE /administrators/1.json
  def destroy
    @administrator = Administrator.find(params[:id])
    @administrator.destroy

    respond_to do |format|
      format.html { redirect_to administrators_url }
      format.json { head :no_content }
    end
  end

  def admin
  end
end

app/helpers/administrators_helper.rb
module AdministratorsHelper
end

app/views/administrators/_form.html.erb
<%= form_for(@administrator) do |f| %>
  <% if @administrator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@administrator.errors.count, "error") %> prohibited this administrator from being saved:</h2>

      <ul>
      <% @administrator.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :password, '密码' %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, '确认' %><br />
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit '确认修改'%>
  </div>
<% end %>

app/views/administrators/admin.html.erb
<h1>营业统计</h1><br/>

<table class="table table-striped">
  <tr>
    <th>最近30天内业额</th>
    <th>最近90天内营业额</th>
    <th>最近365天营业额</th>
  </tr>
  <tr>
    <td>
      <%= Order.find(:all,
      :conditions=>["time >= ? and time <= ?",
      Time.now - 30.day,Time.now]).sum{|order| order.price} %>
    </td>
    <td>
      <%= Order.find(:all,
      :conditions=>["time >= ? and time <= ?",
      Time.now - 90.day,Time.now]).sum{|order| order.price} %>
    </td>
    <td>
      <%= Order.find(:all,
      :conditions=>["time >= ? and time <= ?",
      Time.now - 365.day,Time.now]).sum{|order| order.price} %>
    </td>
  </tr>
</table>
<h1>各电影营业统计</h1><br/>
<table class="table table-striped">
  <tr>
    <th>电影名称</th>
    <th>售出票数</th>
    <th>营业额</th>
  </tr>
  <% Film.all.each do |film| %>
  <tr>
    <td>
      <%= film.title %>
    </td>
    <td>
      <%= film.tickets.find(:all,
      :conditions=>"Onsale='f'").size %>
    </td>
    <td>
      <%= film.tickets.find(:all,
      :conditions=>"Onsale='f'").sum{|t| t.price} %>
    </td>
  </tr>
  <% end %>
</table>



<h1>管理</h1><br/>
<%= link_to '电影管理', films_url, :class=>"btn" %>
<%= link_to '场次管理', tickets_url, :class=>"btn" %>
<%= link_to '更改管理员密码', edit_administrator_path(session[:admin_id]), :class=>"btn" %>

app/views/administrators/edit.html.erb
<h1>更改管理员密码</h1>

<%= render 'form' %>

app/views/administrators/index.html.erb
<h1>Listing administrators</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Password digest</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @administrators.each do |administrator| %>
  <tr>
    <td><%= administrator.username %></td>
    <td><%= administrator.password_digest %></td>
    <td><%= link_to 'Show', administrator %></td>
    <td><%= link_to 'Edit', edit_administrator_path(administrator) %></td>
    <td><%= link_to 'Destroy', administrator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Administrator', new_administrator_path %>

app/views/administrators/new.html.erb
<h1>New administrator</h1>

<%= render 'form' %>

<%= link_to 'Back', administrators_path %>

app/views/administrators/show.html.erb
<p>成功更新！</p>
<style type="text/css" </style>
#notice {
  display: none:
  }
</style>

<p>
  <b>管理员:</b>
  <%= @administrator.username %>
</p>

<p>
  <b>密文密码：</b>
  <%= @administrator.password_digest %>
</p>