config/routes.rb
OnlineCinemaTicket::Application.routes.draw do

  resources :order_lines

  resources :orders

  resources :administrators

  controller :administrators do
    get 'admin' => :admin
  end

  resources :actors

  controller :sessions do
    get 'admin_login'  => :admin_new
    post 'admin_login' => :admin_create
    get 'login'        => :new
    post 'login'       => :create
    delete 'logout'    => :destroy
  end

  resources :store

  controller :store do
    get 'index'      => :index
    get 'show_now'   => :show_now
    get 'show_after' => :show_after
    get 'about'      => :about
  end
    
  resources :accounts 

  controller :accounts do
    get 'newuser' => :new
    get 'detail'  => :detail
  end

  controller :choose do
    get 'show_ticket' => :show_ticket
    get 'show_seat'   => :show_seat
    post 'ensure_order' => :ensure_order
    get 'ensure_order' => :ensure_order
  end
  
  resources :tickets

  resources :films

  controller :film do
    get 'moreinfo' => :moreinfo
  end

  resources :about

  root :to => 'store#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/order_line.rb
class OrderLine < ActiveRecord::Base
  attr_accessible :order_id, :ticket_id
  belongs_to :order
  belongs_to :ticket
end

app/controllers/order_lines_controller.rb
class OrderLinesController < ApplicationController
  # GET /order_lines
  # GET /order_lines.json
  def index
    @order_lines = OrderLine.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @order_lines }
    end
  end

  # GET /order_lines/1
  # GET /order_lines/1.json
  def show
    @order_line = OrderLine.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order_line }
    end
  end

  # GET /order_lines/new
  # GET /order_lines/new.json
  def new
    @order_line = OrderLine.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order_line }
    end
  end

  # GET /order_lines/1/edit
  def edit
    @order_line = OrderLine.find(params[:id])
  end

  # POST /order_lines
  # POST /order_lines.json
  def create
    @order_line = OrderLine.new(params[:order_line])

    respond_to do |format|
      if @order_line.save
        format.html { redirect_to @order_line, notice: 'Order line was successfully created.' }
        format.json { render json: @order_line, status: :created, location: @order_line }
      else
        format.html { render action: "new" }
        format.json { render json: @order_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /order_lines/1
  # PUT /order_lines/1.json
  def update
    @order_line = OrderLine.find(params[:id])

    respond_to do |format|
      if @order_line.update_attributes(params[:order_line])
        format.html { redirect_to @order_line, notice: 'Order line was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_lines/1
  # DELETE /order_lines/1.json
  def destroy
    @order_line = OrderLine.find(params[:id])
    @order_line.destroy

    respond_to do |format|
      format.html { redirect_to order_lines_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/order_lines_helper.rb
module OrderLinesHelper
end

app/views/order_lines/_form.html.erb
<%= form_for(@order_line) do |f| %>
  <% if @order_line.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order_line.errors.count, "error") %> prohibited this order_line from being saved:</h2>

      <ul>
      <% @order_line.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :order_id %><br />
    <%= f.number_field :order_id %>
  </div>
  <div class="field">
    <%= f.label :ticket_id %><br />
    <%= f.number_field :ticket_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/order_lines/edit.html.erb
<h1>Editing order_line</h1>

<%= render 'form' %>

<%= link_to 'Show', @order_line %> |
<%= link_to 'Back', order_lines_path %>

app/views/order_lines/index.html.erb
<h1>Listing order_lines</h1>

<table>
  <tr>
    <th>Order</th>
    <th>Ticket</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @order_lines.each do |order_line| %>
  <tr>
    <td><%= order_line.order_id %></td>
    <td><%= order_line.ticket_id %></td>
    <td><%= link_to 'Show', order_line %></td>
    <td><%= link_to 'Edit', edit_order_line_path(order_line) %></td>
    <td><%= link_to 'Destroy', order_line, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Order line', new_order_line_path %>

app/views/order_lines/new.html.erb
<h1>New order_line</h1>

<%= render 'form' %>

<%= link_to 'Back', order_lines_path %>

app/views/order_lines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Order:</b>
  <%= @order_line.order_id %>
</p>

<p>
  <b>Ticket:</b>
  <%= @order_line.ticket_id %>
</p>


<%= link_to 'Edit', edit_order_line_path(@order_line) %> |
<%= link_to 'Back', order_lines_path %>