config/routes.rb
OnlineCinemaTicket::Application.routes.draw do

  resources :order_lines

  resources :orders

  resources :administrators

  controller :administrators do
    get 'admin' => :admin
  end

  resources :actors

  controller :sessions do
    get 'admin_login'  => :admin_new
    post 'admin_login' => :admin_create
    get 'login'        => :new
    post 'login'       => :create
    delete 'logout'    => :destroy
  end

  resources :store

  controller :store do
    get 'index'      => :index
    get 'show_now'   => :show_now
    get 'show_after' => :show_after
    get 'about'      => :about
  end
    
  resources :accounts 

  controller :accounts do
    get 'newuser' => :new
    get 'detail'  => :detail
  end

  controller :choose do
    get 'show_ticket' => :show_ticket
    get 'show_seat'   => :show_seat
    post 'ensure_order' => :ensure_order
    get 'ensure_order' => :ensure_order
  end
  
  resources :tickets

  resources :films

  controller :film do
    get 'moreinfo' => :moreinfo
  end

  resources :about

  root :to => 'store#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/account.rb
#encoding: utf-8
class Account < ActiveRecord::Base
  attr_accessible :balance, :email, :password,:password_confirmation, :score, :username
  has_secure_password
  has_many :orders
  validates_uniqueness_of :username, :message => "用户名已存在"
  validates_length_of :password, :minimum => 8, :message => "密码太短，至少为8位"
  validates_format_of  :email, :message => "邮箱格式不正确!", :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i  


end

app/models/actor.rb
class Actor < ActiveRecord::Base
  attr_accessible :film_id, :name
  belongs_to :film
end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
  attr_accessible :password, :password_confirmation, :username
  has_secure_password
end

app/models/film.rb
#encoding: utf-8
class Film < ActiveRecord::Base
  attr_accessible :category, :country, :description, :director, :length, :time, :title
  has_many :actors
  has_many :tickets

  validates_presence_of :title, :message => "电影标题不能为空"
    
  
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :account_id, :time, :price
  belongs_to :account
  has_many :order_lines

end

app/models/order_line.rb
class OrderLine < ActiveRecord::Base
  attr_accessible :order_id, :ticket_id
  belongs_to :order
  belongs_to :ticket
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  attr_accessible :colume, :film_id, :price, :room, :row, :time, :onsale
  belongs_to :film
  has_one :order_line

  validates_numericality_of :price
  validates_presence_of :price
  validates_presence_of :room


end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_filter :authorize, :except => :show
  # GET /films
  # GET /films.json
  def index
    @films = Film.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @films }
    end
  end

  # GET /films/1
  # GET /films/1.json
  def show
    @film = Film.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @film }
    end
  end

  # GET /films/new
  # GET /films/new.json
  def new
    @film = Film.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @film }
    end
  end

  # GET /films/1/edit
  def edit
    @film = Film.find(params[:id])
  end

  # POST /films
  # POST /films.json
  def create
    @film = Film.new(params[:film])
    actornames = params[:actors].split(',')
    actornames.each do |actorname|
      actor = Actor.new
      actor.film_id = @film.id
      actor.name = actorname
      @film.actors << actor
    end

    respond_to do |format|
      if @film.save
        format.html { redirect_to @film, notice: 'Film was successfully created.' }
        format.json { render json: @film, status: :created, location: @film }
      else
        format.html { render action: "new" }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /films/1
  # PUT /films/1.json
  def update
    @film = Film.find(params[:id])
    actornames = params[:actors].split(',')
    actornames.each do |actorname|
      actor = Actor.new
      actor.film_id = @film.id
      actor.name = actorname
      @film.actors << actor
    end


    respond_to do |format|
      if @film.update_attributes(params[:film])
        format.html { redirect_to @film, notice: 'Film was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1
  # DELETE /films/1.json
  def destroy
    @film = Film.find(params[:id])
    @film.tickets.destroy_all
    @film.actors.destroy_all
    @film.destroy

    respond_to do |format|
      format.html { redirect_to films_url }
      format.json { head :no_content }
    end
  end

  def moreinfo
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
	public
	def index
	end

	def show_now
		@tmpfilms = Film.find(:all, :conditions => ["time < ?", Time.now])
    @films = []
    @tmpfilms.each do |f|
      can = false
      if f.tickets 
        f.tickets.each do |t|
          if t.time >= Time.now
            can = true
          end
        end
      end
      if can 
        @films << f
      end
    end

	end

	def show_after
		@films = Film.find(:all, :conditions => ["time > ?", Time.now])
	end

	def about
	end

  def authorize
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/choose_helper.rb
module ChooseHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/order_lines_helper.rb
module OrderLinesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<head>
  <title>电影院在线售票系统</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<style type="text/css">
  body {
    padding-top: 60px;
    padding-bottom: 40px;
  }
</style>

<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <div class="brand">在线售票</div>
        <div class="nav-collapse collapse">
          <ul class="nav">
            <li><%= link_to '主页', index_url %></li>
            <li><%= link_to '火热上映', show_now_url %></li>
            <li><%= link_to '即将上映', show_after_url %></li>
            <li><%= link_to '关于我们', about_url %></li>
          </ul>

          <form class="navbar-form pull-right">

            <% if session[:account_id] != nil %>
            当前用户：
            <%= session[:account_username] %>

            <%= link_to '我的账户', detail_url, :class=>"btn" %>
            <%= link_to '退出登录', logout_url, :class=>"btn", :method => :delete %>
            <% elsif session[:admin_id] != nil %>
            <%= link_to '管理',admin_url, :class=>"btn" %>
            <%= link_to '退出登录', logout_url, :method=>"delete",:class=>"btn", :method => :delete %>
            <% else %>
            <%= link_to '用户登录', login_url, :class=>'btn' %>
            <%= link_to '注册', newuser_url, :class=>'btn' %>
            <%= link_to '管理员登录', admin_login_url, :class=>'btn' %>
            <% end %>
          </form>


        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>


  <div class="container">
  <% if flash[:notice] %>
  <h1 id="notice"><%= flash[:notice] %></h1> 
  <% end %>
    <%= yield %>
  </div>

</body>
</html>